### ISSUE TITLE
Fix simple completion

### ISSUE THREAD

**Issue by hugoduncan** [pallet/ritz#15]
Simple completion seems to be hanging in some cases.  Ensure that test cases are added for simple completion.

**Comment by tbatchelli** [comment]
This is the exception as captured by ritz itself 

clojure.lang.LazySeq cannot be cast to clojure.lang.IDeref
  [Thrown java.lang.ClassCastException]

Restarts:
 0: [CONTINUE] Pass exception to program
 1: [ABORT] Return to SLIME's top level.
 2: [IGNORE] Do not enter debugger for this exception type

Backtrace:
  0: clojure.core/deref (core.clj:1765)
  1: ritz.repl-utils.completion/classes-on-path (completion.clj:59)
  2: ritz.repl-utils.completion/simple-completion (completion.clj:102)
  3: ritz.commands.completion/simple-completions (completion.clj:11)
  4: clojure.lang.Var.invoke (Var.java:373)
  5: clojure.lang.AFn.applyToHelper (AFn.java:169)
  6: clojure.lang.Var.applyTo (Var.java:482)
  7: clojure.core/apply (core.clj:542)
  8: ritz.swank.core/execute-slime-fn\* (core.clj:49)
  9: ritz.swank.core/execute-slime-fn/fn--1309 (core.clj:56)
 --more--

**Comment by hugoduncan** [comment]
Fixed in 0.3.0
