### ISSUE TITLE
Cannot locate file error right after slime-connect

### ISSUE THREAD

**Issue by mathematical-systems** [pallet/ritz#22]
My slime configuration in .emacs is:

(require 'slime)
(slime-setup '(slime-fancy slime-tramp))

And in project.clj:

  :plugins [[lein-ritz "0.3.0-SNAPSHOT"]]
  :resource-paths ["/usr/lib/jvm/java-7-openjdk-i386/lib/tools.jar"]
  :hooks [ritz.add-sources]

I got the following errors after slime-connect, but repl works after I call the ABORT restart.

Any idea how to fix it?

Could not locate swank/util__init.class or swank/util.clj on classpath: 
  [Thrown java.io.FileNotFoundException]

Restarts:
 0: [CONTINUE] Pass exception to program
 1: [ABORT] Return to SLIME's top level.
 2: [IGNORE] Do not enter debugger for this exception type
 3: [IGNORE-MSG] Do not enter debugger for this exception message
 4: [IGNORE-CATCH] Do not enter debugger for exceptions with catch location clojure.core.*
 5: [IGNORE-LOC] Do not enter debugger for exceptions with throw location clojure.core.*

Backtrace:
  0: clojure.core/load/fn--4610 (core.clj:5385)
  1: clojure.core$load.doInvoke (core.clj:5385)
  2: clojure.lang.RestFn.invoke (RestFn.java:408)
  3: clojure.core/load-one (core.clj:5200)
  4: clojure.core$load_lib.doInvoke (core.clj:5237)
  5: clojure.lang.RestFn.applyTo (RestFn.java:142)
  6: clojure.core/apply (core.clj:602)
  7: clojure.core$load_libs.doInvoke (core.clj:5275)
  8: clojure.lang.RestFn.applyTo (RestFn.java:137)
  9: clojure.core/apply (core.clj:604)
 10: clojure.core$use.doInvoke (core.clj:5363)
 11: clojure.lang.RestFn.invoke (RestFn.java:457)
 12: ritz.commands.contrib.swank-c-p-c/eval3598/loading--4505--auto----3599 (swank_c_p_c.clj:1)
 13: ritz.commands.contrib.swank-c-p-c/eval3598 (swank_c_p_c.clj:1)
 14: clojure.lang.Compiler.eval (Compiler.java:6465)
 15: clojure.lang.Compiler.eval (Compiler.java:6455)
 16: clojure.lang.Compiler.load (Compiler.java:6902)
 17: clojure.lang.RT.loadResourceScript (RT.java:357)
 18: clojure.lang.RT.loadResourceScript (RT.java:348)
 19: clojure.lang.RT.load (RT.java:427)
 20: clojure.lang.RT.load (RT.java:398)
 21: clojure.core/load/fn--4610 (core.clj:5386)
 22: clojure.core$load.doInvoke (core.clj:5385)
 23: clojure.lang.RestFn.invoke (RestFn.java:408)
 24: clojure.core/load-one (core.clj:5200)
 25: clojure.core$load_lib.doInvoke (core.clj:5237)
 26: clojure.lang.RestFn.applyTo (RestFn.java:142)
 27: clojure.core/apply (core.clj:602)
 28: clojure.core$load_libs.doInvoke (core.clj:5271)
 29: clojure.lang.RestFn.applyTo (RestFn.java:137)
 30: clojure.core/apply (core.clj:602)
 31: clojure.core$require.doInvoke (core.clj:5352)
 32: clojure.lang.RestFn.invoke (RestFn.java:408)
 33: ritz.commands.contrib/swank-require/fn--3208 (contrib.clj:12)
 34: ritz.commands.contrib/swank-require (contrib.clj:10)
 35: clojure.lang.Var.invoke (Var.java:405)
 36: clojure.lang.AFn.applyToHelper (AFn.java:163)
 37: clojure.lang.Var.applyTo (Var.java:518)
 38: clojure.core/apply (core.clj:602)
 39: ritz.swank.core/execute-slime-fn\* (core.clj:86)
 40: ritz.swank.core/execute-slime-fn/fn--1639 (core.clj:93)
 41: ritz.swank/eval-for-emacs (swank.clj:34)
 42: ritz.swank/dispatch-event (swank.clj:113)
 43: ritz.swank/handle-message/fn--2479 (swank.clj:197)
 44: clojure.lang.AFn.call (AFn.java:18)
 45: java.util.concurrent.FutureTask$Sync.innerRun (FutureTask.java:334)
 46: java.util.concurrent.FutureTask.run (FutureTask.java:166)
 47: java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1110)
 48: java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:603)
 49: java.lang.Thread.run (Thread.java:722)

**Comment by huangjs** [comment]
Oh, the error is from slime-c-p-c contrib package, i currently disabled it and use slime-fuzzy only.

**Comment by hugoduncan** [comment]
Break on exception is now off by default, so this sort of issue should not occur on startup.
