### ISSUE TITLE
Try-catch fail in repl?

### ISSUE THREAD

**Issue by huangjs** [pallet/ritz#23]
The following expression will cause the debugger to pop up, and I have to choose "Pass exception to program" which is quite annoying

(try (/ 1 0) (catch Exception e e))

Is there a way to disable that?

**Comment by hugoduncan** [comment]
Break on exception is now off by default. You can also filter exceptions by choosing one of the 'Ignore' restarts. The exception filters can be managed in M-x slime-selector f
