### ISSUE TITLE
Is it possible to hook the functionality of nrepl-jack-in for ritz 

### ISSUE THREAD

**Issue by murtaza52** [pallet/ritz#49]
Hi,

Is it possible to start both the nrepl and connect to it one step. While using clojure-swank I can do it using clojure-jack-in. 

In ritz , its a two step process - lein2 repl and M-x nrepl. Is it possible to implement it using nrepl-jack-in ?

Thanks,
Murtaza

**Comment by hugoduncan** [comment]
`nrepl-ritz-jack-in` is provided in `nrepl-ritz.el`
