### ISSUE TITLE
Set *compile-path*

### ISSUE THREAD

**Issue by neotyk** [pallet/ritz#5]
When running lein swank-clj latest version, connecting with slime-connect.
I can get very nice repl debugging.
If I try to compile a file from project that I get in _Messages_:
   java.lang.Exception: _compile-path_ not set (setup.clj:0)
Where setup.clj is file I've tried to compile.

**Comment by hugoduncan** [comment]
If you have a use case for compile-file-for-emacs actually doing compilation, please let me know…

**Comment by neotyk** [comment]
Great, I'll take it for a spin this evening.
Thanks :-)
