### ISSUE TITLE
Debugger does not clear :abort-to-level Flag

### ISSUE THREAD

**Issue by juergenhoetzel** [pallet/ritz#51]
Enable _(slime-break-on-exception)_

  user> (throw (Exception. "Foo"))
  ; Evaluation aborted on java.lang.RuntimeException: java.lang.Exception: Foo. -> Debugger invoked     (Aborting to toplevel)
  user> (throw (Exception. "Foo"))
  ; Evaluation aborted on java.lang.RuntimeException: java.lang.Exception: Foo. -> Debugger invoked   (Aborting to toplevel)
  user> (throw (Exception. "Foo"))
  ; Evaluation aborted on java.lang.RuntimeException: java.lang.Exception: Foo. -> Debugger not invoked 

The Debugger is not invoked because the _:abort-to-level_  flag which is maintained for each thread is not cleared.

Workaround:

use the _M-x slime-selector t_ and kill the
_ritz-nnnn threads_, so that they don't get reused.

**Comment by hugoduncan** [comment]
Fixed in 0.6
