### ISSUE TITLE
Error: cannot resolve ritz.add-sources/activate hook

### ISSUE THREAD

**Issue by cola-zero** [pallet/ritz#66]
When I add  `:hooks [ritz.add-sources]` to .profiles.clj and run `lein ritz-nrepl`, I get some error messages "Error: cannot resolve ritz.add-sources/activate hook".
I'm using Leiningen 2.0.0-preview10.
And [this](https://gist.github.com/4259354) is log of my environment.

This is obvious because lein calls `activate` function in namespaces which specified in `:hooks`.
https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md#hooks

But how the activate function should be? or, are there any way?

**Comment by dgtized** [comment]
I can confirm having encountered the same error. I'm happy to try and fix it given some basic suggestions on what the intent of this behavior is supposed to be.

**Comment by cola-zero** [comment]
We can close this because of 15819fbd850a1b12eb4759af2c804b4557e33107.
