### ISSUE TITLE
clojure-maven-plugin support

### ISSUE THREAD

**Issue by digash** [pallet/ritz#7]
Would be nice to have a backward compatible api for clojure-maven-plugin to work.

Exception in thread "main" java.io.FileNotFoundException: Could not locate swank/swank__init.class or swank/swank.clj on classpath:  (NO_SOURCE_FILE:0)

**Comment by hugoduncan** [comment]
Not sure what the best way forward on this is.

I have a local swank-clj mojo for clojure-maven-plugin, and I could ask talios whether he would be willing to add it to clojure-maven-plugin.

A backward compatible adapter would also be possible, but I wouldn't want it in the main jar, so that swank-clojure and swank-clj can both be present in dev dependencies without conflict.

**Comment by digash** [comment]
Having it in the clojure-maven-plugin, would be the best solution, but I would not mind including another jar in dependencies for backward compatabillity or switching between swank-clojure and swank-clj dependencies jars.

**Comment by digash** [comment]
I could not find a swank-clj mojo in your fork of clojure-maven-plugin. Could you push it out, I would like to test it out.

**Comment by hugoduncan** [comment]
https://github.com/hugoduncan/clojure-maven-plugin/tree/feature%2Fadd-swank-clj-task

**Comment by hugoduncan** [comment]
There is now a ritz goal in the zi plugin https://github.com/pallet/zi

**Comment by digash** [comment]
Tried it but could not make it work on my current project,

Exception in thread "main" java.lang.OutOfMemoryError: PermGen space

I need to specify some vmargs for my project to even compile, which is not supported in zi yet.

```
      <vmargs>-verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xms500m -Xmx2000m -XX:MaxPermSize=128m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -Xloggc:"${project.build.directory}${file.separator}clojure-maven-${user.name}.gc"</vmargs>
```

**Comment by hugoduncan** [comment]
zi doesn't actually fork a process, so you can specify those with MAVEN_OPTS. zi should support a forked execution model.

**Comment by digash** [comment]
I got it now, using MAVEN_OPTS. Thanks for all the great work.
