### ISSUE TITLE
Clojure 1.5.1 compatibility

### ISSUE THREAD

**Issue by ihat** [pallet/ritz#91]
The current release of lein-ritz (0.7.0) is locked to clojure-1.4.0. What are the blockers to get it to be compatibile with clojure-1.5.1?

**Comment by amalloy** [comment]
It works fine on 1.5.x. lein itself runs on clojure 1.4, but the project jvm uses your own clojure version. This is the case for most lein plugins.

**Comment by amalloy** [comment]
(recommend @hugoduncan closes this issue as works-for-me)

**Comment by hugoduncan** [comment]
@amalloy can you confirm you are running ritz 0.7.0?

**Comment by amalloy** [comment]
@hugoduncan My ~/.lein/profiles.clj contains `[lein-ritz "0.7.0"]` and `[ritz/ritz-nrepl-middleware "0.7.0"]`, and I'm running whatever elisp I got from marmalade via the getting-started instructions.

**Comment by amalloy** [comment]
And I certainly haven't exercised _all_ the ritz features, but eg I can compile code without locals-clearing and see the locals in my stacktrace, in a repl for which `*clojure-version*` returns 1.5.1.

**Comment by hugoduncan** [comment]
Thanks, closing.
